version: '3'
services:
  db:
    image: mysql:5.7.30
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0
    user: "1000:50"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/aso-diary-web-rails
    ports:
      - "3000:3000"
    links:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /phpmyadmin
